import AppKit
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
import ScoutCore

/// Generates the small sample files the demo routines start from (a one-page PDF and a screenshot-sized PNG).
enum DemoFiles {
    static func pdf(title: String) throws -> Data {
        let data = NSMutableData()
        var box = CGRect(x:0,y:0,width:612,height:792)
        guard let consumer = CGDataConsumer(data:data), let context = CGContext(consumer:consumer,mediaBox:&box,nil) else { throw ScoutError.message("Could not create the sample PDF.") }
        context.beginPDFPage(nil)
        context.setFillColor(CGColor(red:0.1,green:0.42,blue:0.36,alpha:1)); context.fill(CGRect(x:0,y:700,width:612,height:92))
        let attributes: [NSAttributedString.Key:Any] = [.font:NSFont.systemFont(ofSize:28,weight:.bold),.foregroundColor:NSColor.white]
        let line = CTLineCreateWithAttributedString(NSAttributedString(string:title,attributes:attributes))
        context.textPosition = CGPoint(x:48,y:732); CTLineDraw(line,context)
        let body = CTLineCreateWithAttributedString(NSAttributedString(string:"Sample invoice generated by Handoff for practice. Amount due: $420.00",attributes:[.font:NSFont.systemFont(ofSize:14),.foregroundColor:NSColor.black]))
        context.textPosition = CGPoint(x:48,y:640); CTLineDraw(body,context)
        context.endPDFPage(); context.closePDF()
        return data as Data
    }
    static func png(width: Int, height: Int) throws -> Data {
        guard let context = CGContext(data:nil,width:width,height:height,bitsPerComponent:8,bytesPerRow:0,space:CGColorSpaceCreateDeviceRGB(),bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue) else { throw ScoutError.message("Could not create the sample image.") }
        context.setFillColor(CGColor(red:0.95,green:0.97,blue:0.96,alpha:1)); context.fill(CGRect(x:0,y:0,width:width,height:height))
        context.setFillColor(CGColor(red:0.1,green:0.42,blue:0.36,alpha:1)); context.fill(CGRect(x:0,y:height-120,width:width,height:120))
        for i in 0..<6 { context.setFillColor(CGColor(gray:0.85-Double(i)*0.05,alpha:1)); context.fill(CGRect(x:80,y:height-260-i*90,width:width-160,height:60)) }
        guard let image = context.makeImage() else { throw ScoutError.message("Could not create the sample image.") }
        let output = NSMutableData()
        guard let writer = CGImageDestinationCreateWithData(output,UTType.png.identifier as CFString,1,nil) else { throw ScoutError.message("Could not save the sample image.") }
        CGImageDestinationAddImage(writer,image,nil); guard CGImageDestinationFinalize(writer) else { throw ScoutError.message("Could not save the sample image.") }
        return output as Data
    }
}
